kind: pipeline
type: docker
name: build

concurrency:
  limit: 1

steps:
  - name: Install dependencies
    image: node:lts
    commands:
      - git config --global url."https://${{ GITHUB_TOKEN }}@github.com/".insteadOf ssh://git@github.com/
      - npm ci
    environment:
      GITHUB_TOKEN:
        from_secret: github_token

  - name: Build app
    image: node:lts
    commands:
      - npm run build

  - name: Upload to bucket
    image: plugins/s3
    when:
      branch:
        - master
    settings:
      bucket: nabais.me
      source: build/**/*
      endpoint: http://minio:9000
      region: eu-west-1
      strip_prefix: build/
      path_style: true
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key

trigger:
  event:
    - push
    - custom
