name: CI

on:
  push:
    branches:
      - master
      - dependabot/**
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - master

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit --prefer-offline

      - name: Lint
        run: npm run lint
        env:
          CI: true

      - name: Test
        run: npm run test:ci
        env:
          CI: true
