name: CI

on:
  push:
    branches:
      - $default-branch
      - dependabot/**
  pull_request:
    branches:
      - $default-branch

env:
  CI: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 'package.json'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit --prefer-offline

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test
